version: '3.8'

services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      # This volume maps the 'applications' folder on your computer to a folder
      # with the same name inside the container, so generated files persist.
      - ./applications:/app/applications

      # This makes the base resume and variables files available inside the container.
      - ./manikesh_resume_ats.yaml:/app/manikesh_resume_ats.yaml
      - ./app/backend/variables.yaml:/app/variables.yaml # This line was missing

    env_file:
      - ./app/backend/.env
    networks:
      - app-network

  frontend:
    build: ./app/frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
