version: '3.8'

services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./applications:/app/applications
      - ./base_resume_fixed.yaml:/app/base_resume_fixed.yaml
      - ./app/backend/variables.yaml:/app/variables.yaml

    env_file:
      - ./app/backend/.env
    networks:
      - app-network

  frontend:
    build: ./app/frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge